project_type: ios
test:
  checksytle:
    ignore: false
    command: fastlane lint

  build:
    ignore: false
    command: fastlane build

  test:
    ignore: false
    command: fastlane test
     
  coverage:
    ignore: false
    command: fastlane coverage
