project_type: ios
test:
  checksytle:
    ignore: false
    command: fastlane lint
    
  test:
    ignore: false
    command: fastlane test
     
  coverage:
    ignore: false
    command: fastlane coverage
